# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/memormou/DX/12_5_6am_SE/search_engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/memormou/DX/12_5_6am_SE/search_engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/memormou/DX/12_5_6am_SE/search_engine/CMakeFiles /Users/memormou/DX/12_5_6am_SE/search_engine/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/memormou/DX/12_5_6am_SE/search_engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named csv_demo

# Build rule for target.
csv_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 csv_demo
.PHONY : csv_demo

# fast build rule for target.
csv_demo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/csv_demo.dir/build.make CMakeFiles/csv_demo.dir/build
.PHONY : csv_demo/fast

#=============================================================================
# Target rules for targets named hashtable_demo

# Build rule for target.
hashtable_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hashtable_demo
.PHONY : hashtable_demo

# fast build rule for target.
hashtable_demo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashtable_demo.dir/build.make CMakeFiles/hashtable_demo.dir/build
.PHONY : hashtable_demo/fast

#=============================================================================
# Target rules for targets named stem_demo

# Build rule for target.
stem_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stem_demo
.PHONY : stem_demo

# fast build rule for target.
stem_demo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stem_demo.dir/build.make CMakeFiles/stem_demo.dir/build
.PHONY : stem_demo/fast

#=============================================================================
# Target rules for targets named boost_demo

# Build rule for target.
boost_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 boost_demo
.PHONY : boost_demo

# fast build rule for target.
boost_demo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_demo.dir/build.make CMakeFiles/boost_demo.dir/build
.PHONY : boost_demo/fast

#=============================================================================
# Target rules for targets named search_engine

# Build rule for target.
search_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 search_engine
.PHONY : search_engine

# fast build rule for target.
search_engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/build
.PHONY : search_engine/fast

#=============================================================================
# Target rules for targets named fort_dev

# Build rule for target.
fort_dev: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fort_dev
.PHONY : fort_dev

# fast build rule for target.
fort_dev/fast:
	$(MAKE) $(MAKESILENT) -f third_party/libfort/CMakeFiles/fort_dev.dir/build.make third_party/libfort/CMakeFiles/fort_dev.dir/build
.PHONY : fort_dev/fast

DocumentProcessor.o: DocumentProcessor.cpp.o

.PHONY : DocumentProcessor.o

# target to build an object file
DocumentProcessor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/DocumentProcessor.cpp.o
.PHONY : DocumentProcessor.cpp.o

DocumentProcessor.i: DocumentProcessor.cpp.i

.PHONY : DocumentProcessor.i

# target to preprocess a source file
DocumentProcessor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/DocumentProcessor.cpp.i
.PHONY : DocumentProcessor.cpp.i

DocumentProcessor.s: DocumentProcessor.cpp.s

.PHONY : DocumentProcessor.s

# target to generate assembly for a file
DocumentProcessor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/DocumentProcessor.cpp.s
.PHONY : DocumentProcessor.cpp.s

HashTable.o: HashTable.cpp.o

.PHONY : HashTable.o

# target to build an object file
HashTable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashtable_demo.dir/build.make CMakeFiles/hashtable_demo.dir/HashTable.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/HashTable.cpp.o
.PHONY : HashTable.cpp.o

HashTable.i: HashTable.cpp.i

.PHONY : HashTable.i

# target to preprocess a source file
HashTable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashtable_demo.dir/build.make CMakeFiles/hashtable_demo.dir/HashTable.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/HashTable.cpp.i
.PHONY : HashTable.cpp.i

HashTable.s: HashTable.cpp.s

.PHONY : HashTable.s

# target to generate assembly for a file
HashTable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashtable_demo.dir/build.make CMakeFiles/hashtable_demo.dir/HashTable.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/HashTable.cpp.s
.PHONY : HashTable.cpp.s

avl.o: avl.cpp.o

.PHONY : avl.o

# target to build an object file
avl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/avl.cpp.o
.PHONY : avl.cpp.o

avl.i: avl.cpp.i

.PHONY : avl.i

# target to preprocess a source file
avl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/avl.cpp.i
.PHONY : avl.cpp.i

avl.s: avl.cpp.s

.PHONY : avl.s

# target to generate assembly for a file
avl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/avl.cpp.s
.PHONY : avl.cpp.s

boost_demo.o: boost_demo.cpp.o

.PHONY : boost_demo.o

# target to build an object file
boost_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_demo.dir/build.make CMakeFiles/boost_demo.dir/boost_demo.cpp.o
.PHONY : boost_demo.cpp.o

boost_demo.i: boost_demo.cpp.i

.PHONY : boost_demo.i

# target to preprocess a source file
boost_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_demo.dir/build.make CMakeFiles/boost_demo.dir/boost_demo.cpp.i
.PHONY : boost_demo.cpp.i

boost_demo.s: boost_demo.cpp.s

.PHONY : boost_demo.s

# target to generate assembly for a file
boost_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_demo.dir/build.make CMakeFiles/boost_demo.dir/boost_demo.cpp.s
.PHONY : boost_demo.cpp.s

csv_demo.o: csv_demo.cpp.o

.PHONY : csv_demo.o

# target to build an object file
csv_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/csv_demo.dir/build.make CMakeFiles/csv_demo.dir/csv_demo.cpp.o
.PHONY : csv_demo.cpp.o

csv_demo.i: csv_demo.cpp.i

.PHONY : csv_demo.i

# target to preprocess a source file
csv_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/csv_demo.dir/build.make CMakeFiles/csv_demo.dir/csv_demo.cpp.i
.PHONY : csv_demo.cpp.i

csv_demo.s: csv_demo.cpp.s

.PHONY : csv_demo.s

# target to generate assembly for a file
csv_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/csv_demo.dir/build.make CMakeFiles/csv_demo.dir/csv_demo.cpp.s
.PHONY : csv_demo.cpp.s

hashtable_demo.o: hashtable_demo.cpp.o

.PHONY : hashtable_demo.o

# target to build an object file
hashtable_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashtable_demo.dir/build.make CMakeFiles/hashtable_demo.dir/hashtable_demo.cpp.o
.PHONY : hashtable_demo.cpp.o

hashtable_demo.i: hashtable_demo.cpp.i

.PHONY : hashtable_demo.i

# target to preprocess a source file
hashtable_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashtable_demo.dir/build.make CMakeFiles/hashtable_demo.dir/hashtable_demo.cpp.i
.PHONY : hashtable_demo.cpp.i

hashtable_demo.s: hashtable_demo.cpp.s

.PHONY : hashtable_demo.s

# target to generate assembly for a file
hashtable_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashtable_demo.dir/build.make CMakeFiles/hashtable_demo.dir/hashtable_demo.cpp.s
.PHONY : hashtable_demo.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/main.cpp.s
.PHONY : main.cpp.s

stem_demo.o: stem_demo.cpp.o

.PHONY : stem_demo.o

# target to build an object file
stem_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stem_demo.dir/build.make CMakeFiles/stem_demo.dir/stem_demo.cpp.o
.PHONY : stem_demo.cpp.o

stem_demo.i: stem_demo.cpp.i

.PHONY : stem_demo.i

# target to preprocess a source file
stem_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stem_demo.dir/build.make CMakeFiles/stem_demo.dir/stem_demo.cpp.i
.PHONY : stem_demo.cpp.i

stem_demo.s: stem_demo.cpp.s

.PHONY : stem_demo.s

# target to generate assembly for a file
stem_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stem_demo.dir/build.make CMakeFiles/stem_demo.dir/stem_demo.cpp.s
.PHONY : stem_demo.cpp.s

utils.o: utils.cpp.o

.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i

.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s

.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/utils.cpp.s
.PHONY : utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... boost_demo"
	@echo "... csv_demo"
	@echo "... fort_dev"
	@echo "... hashtable_demo"
	@echo "... search_engine"
	@echo "... stem_demo"
	@echo "... DocumentProcessor.o"
	@echo "... DocumentProcessor.i"
	@echo "... DocumentProcessor.s"
	@echo "... HashTable.o"
	@echo "... HashTable.i"
	@echo "... HashTable.s"
	@echo "... avl.o"
	@echo "... avl.i"
	@echo "... avl.s"
	@echo "... boost_demo.o"
	@echo "... boost_demo.i"
	@echo "... boost_demo.s"
	@echo "... csv_demo.o"
	@echo "... csv_demo.i"
	@echo "... csv_demo.s"
	@echo "... hashtable_demo.o"
	@echo "... hashtable_demo.i"
	@echo "... hashtable_demo.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... stem_demo.o"
	@echo "... stem_demo.i"
	@echo "... stem_demo.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

